### ISSUE TITLE
Make it work with GridFieldEditableColumns

### ISSUE THREAD

**Issue by Firesphere** [colymba/GridFieldGalleryTheme#19]
EditableColumns does work, but when you try to go to the editable field, the balloon disappears, therefor, not working anymore.

**Comment by colymba** [comment]
I haven't used `GridFieldEditableColumns`... do you have a screenshot or something to help understand the issue a bit better?

**Comment by Firesphere** [comment]
Yes, here's what it looks like when I hover an image

![editable](https://cloud.githubusercontent.com/assets/680570/10579343/c092a672-7677-11e5-93c6-48c78cafe602.PNG)

But when I try to go to the formfields, the balloon disappears.
